name: Lint

on:
  workflow_call:
    inputs:
      php-version:
        required: true
        type: string

jobs:
  pint:
    uses: itinerare/github-actions/.github/workflows/pint.yml@main
    with:
      php-version: '8.1'
    concurrency:
      group: ci-${{ github.head_ref || github.ref_name }}

  blade-formatter:
    uses: itinerare/github-actions/.github/workflows/blade_formatter.yml@main
    concurrency:
      group: ci-${{ github.head_ref || github.ref_name }}